import type { Metadata } from 'next'
import { Roboto_Flex } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

import './globals.css'

const roboto = Roboto_Flex({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shop',
  description: 'Generated by Anant',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className='chatbot-container px-8 lg:px-12'>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
