import os
ASTRA_DB_NAMESPACE = os.getenv("ASTRA_DB_NAMESPACE")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ASTRA_DB_ID = os.getenv("ASTRA_DB_ID")
ASTRA_DB_REGION = os.getenv("ASTRA_DB_REGION")
ASTRA_DB_APPLICATION_TOKEN = os.getenv("ASTRA_DB_APPLICATION_TOKEN")
